name: CI

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install gawk
        run: |
          apt update -y
          apt install -y gawk

      - name: Run tests
        run: |
          awk -f riss.awk test.md >tmp.md
          diff tmp.md test_output.md

      - name: Check formatting
        run: |
          gawk --pretty-print -f riss.awk
          diff awkprof.out riss.awk
